/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIPanels.ListPanels;

import UIPanels.ListPanels.BaseListPanel;
import javax.swing.JTable;

/**
 *
 * @author arthur
 */
public class ImportListPanel extends BaseListPanel {

    /**
     * Creates new form PackageListPanel
     */
    public ImportListPanel() {
        initComponents();
    }
    
    @Override
    protected JTable table(){
        return importTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        importTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imports"
            }
        ));
        jScrollPane1.setViewportView(importTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable importTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
