/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIPanels.EditPanels;

import UIPanels.BasePanel;

/**
 *
 * @author arthur
 */
public class ModelEditPanel extends BasePanel {

    /**
     * Creates new form ModelEditPanel
     */
    public ModelEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentEditor = new javax.swing.JTabbedPane();
        sourceEditor = new UIPanels.EditPanels.SourceEditPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        commentEditor.addTab("Source", sourceEditor);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        commentEditor.addTab("Comment", jScrollPane1);

        add(commentEditor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane commentEditor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private UIPanels.EditPanels.SourceEditPanel sourceEditor;
    // End of variables declaration//GEN-END:variables
}
