/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIPanels.EditPanels;

import java.awt.Color;
import javax.swing.text.AttributeSet;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 *
 * @author arthur
 */
public class SourceEditPanel extends BaseEditPanel {
    private final StyleContext cont = StyleContext.getDefaultStyleContext();
    private final AttributeSet attr = 
            cont.addAttribute(cont.getEmptySet(), 
                    StyleConstants.Foreground, Color.BLUE);
    private DefaultStyledDocument doc;
    private StyleContext context;
    private SimpleAttributeSet attributes;

    /**
     * Creates new form SourceEditPanel
     */
    public SourceEditPanel() {
        doc = new DefaultStyledDocument();
        context = new StyleContext();
        initComponents();
        this.sourceEditPane.setStyledDocument(doc);
    }
    
    private StyleContext setUpContext(){
        StyleContext cont = new StyleContext();
        cont.addStyle("private", null);
        return cont;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        sourceEditPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(sourceEditPane);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane sourceEditPane;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void applyChanges() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void revertChanges() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
