/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIShells;

import Exceptions.NameAlreadyExistsException;
import Models.PackageModel;
import UIModels.PackageSelectionShellModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author arthur
 */
public class AddNewPackageShell extends BaseUIShell {
    private PackageSelectionShellModel model;
    private PackageModel newPackage;
    
    private static AddNewPackageShell instance = null;

    /**
     * Creates new form AddNewPackageShell
     */
    protected AddNewPackageShell(PackageSelectionShellModel model) {
        this.model = model;
        newPackage = new PackageModel(model.selectedProject(), new String());
        initComponents();
        this.packageNameField.getDocument().addDocumentListener(this.setUpDocListener());
        this.setVisible(true);
    }
    
    public static AddNewPackageShell getInstance(PackageSelectionShellModel model){
        if(instance == null)
            instance = new AddNewPackageShell(model);
        return instance;
    }
    
    public static void closeInstance(){
        if(instance != null){
            instance.signalClosedAndDispose();
            instance = null;
        }
    }
    
    private boolean isPackageValid(){
        if(this.newPackage.name().compareTo(new String()) == 0)
            return false;
        return model.selectedProject().okToAddPackage(this.packageNameField.getText());
    }
    
    private DocumentListener setUpDocListener(){
        return new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                updatePackage();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                updatePackage();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {}
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packageDetailsField = new javax.swing.JTextArea();
        packageNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addPackageButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        packageDetailsField.setColumns(20);
        packageDetailsField.setRows(5);
        jScrollPane1.setViewportView(packageDetailsField);

        jLabel1.setText("Package Name: ");

        addPackageButton.setText("Create");
        addPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPackageButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(packageNameField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPackageButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(packageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPackageButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPackageButtonActionPerformed
        if(this.isPackageValid())
            try {
                model.addPackage(newPackage);
                this.dispose();
        } catch (NameAlreadyExistsException ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage(), "Package Not Valid", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_addPackageButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.signalClosedAndDispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPackageButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea packageDetailsField;
    private javax.swing.JTextField packageNameField;
    // End of variables declaration//GEN-END:variables

    
    private void updatePackage(){
        newPackage.setName(this.packageNameField.getText());
    }
    
    @Override
    public void signalClosedAndDispose(){
        this.dispose();
    }
}
