/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIShells;

import MainBase.SortedList;
import Models.*;
import Types.ClassType;
import UIModels.BrowserUIController;
import UIPanels.BasePanel;

/**
 *
 * @author Arthur
 */
public class SystemBrowserShell extends BaseUIShell {
    /**
     * Creates new form SystemBrowserShell
     */
    public SystemBrowserShell() {
        initComponents();
    }
    
    public SystemBrowserShell(BrowserUIController model){
        this();
        this.setModel(model);
        this.setVisible(true);
    }
    
    @Override
    protected BrowserUIController controller(){
        return (BrowserUIController) controller;
    }
    
    private void setModel(BrowserUIController aController){
        controller = aController;
        for(BasePanel bp : this.myPanels())
            bp.setModel(aController);
    }
    
    @Override
    protected SortedList<BasePanel> myPanels(){
        return super.myPanels()
                .addElm(packageTree)
                .addElm(classBrowserPanel)
                .addElm(modelEditPanel);
    }
    
    private boolean checkModelProject(BaseModel aModel){
        return aModel.getProject() == this.controller().getSelectedProject();
    }
    
    @Override
    public void modelAdded(BaseModel newModel){
        if(!this.checkModelProject(newModel))
            return;
        super.modelAdded(newModel);
    }
    @Override
    public void modelRemoved(BaseModel aModel){
        if(!this.checkModelProject(aModel))
            return;
        super.modelRemoved(aModel);
    }
    @Override
    public void modelChanged(BaseModel aModel){
        if(!this.checkModelProject(aModel))
            return;
        super.modelChanged(aModel);
    }

    public ClassType getSelectedVarType(){
        return this.classBrowserPanel.getSelectedVarType();
    }
    public ClassType getSelectedMethodType(){
        return this.classBrowserPanel.getSelectedMethodType();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        classBrowserPanel = new UIPanels.SelectedClassPanel();
        packageTree = new UIPanels.TreePanels.PackageTreePanel();
        modelEditPanel = new UIPanels.ModelEditPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addPackageMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(250);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane1.setDividerLocation(125);
        jSplitPane1.setRightComponent(classBrowserPanel);
        jSplitPane1.setLeftComponent(packageTree);

        jSplitPane2.setTopComponent(jSplitPane1);
        jSplitPane2.setRightComponent(modelEditPanel);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        addPackageMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addPackageMenuItem.setText("Add Package");
        jMenu1.add(addPackageMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemBrowserShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemBrowserShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemBrowserShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemBrowserShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemBrowserShell().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPackageMenuItem;
    private UIPanels.SelectedClassPanel classBrowserPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private UIPanels.ModelEditPanel modelEditPanel;
    private UIPanels.TreePanels.PackageTreePanel packageTree;
    // End of variables declaration//GEN-END:variables

}
