/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIShells.UIPanels;

import UIModels.UIPanelsModels.ClassBrowserPanelModel;

/**
 *
 * @author Arthur
 */
public class ClassBrowserPanel extends javax.swing.JPanel {
    private ClassBrowserPanelModel model;

    /**
     * Creates new form ClassBrowserPanel
     */
    public ClassBrowserPanel() {
        initComponents();
    }
    public ClassBrowserPanel(ClassBrowserPanelModel model){
        this.model = model;
        initComponents();
        this.setUpModels();
        this.setVisible(true);
    }
    
    private void setUpModels(){
        this.classMethodList.setModel(model.getClassMethodList());
        this.instanceMethodList.setModel(model.getInstMethodList());
        this.classVaraibleList.setModel(model.getClassVarsList());
        this.instanceVariableList.setModel(model.getInstVarList());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        instanceVariableList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        classVaraibleList = new javax.swing.JList();
        addVariableButton = new javax.swing.JButton();
        variableLabel = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        instanceMethodList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        classMethodList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        constructorList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        removeVariableButton = new javax.swing.JButton();
        addMetodButton = new javax.swing.JButton();
        removeMethodButton = new javax.swing.JButton();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jScrollPane1.setViewportView(instanceVariableList);

        jTabbedPane1.addTab("Instance Variables", jScrollPane1);

        jScrollPane2.setViewportView(classVaraibleList);

        jTabbedPane1.addTab("Static Variables", jScrollPane2);

        addVariableButton.setText("+");

        variableLabel.setText("Variables");

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jScrollPane3.setViewportView(instanceMethodList);

        jTabbedPane2.addTab("Instance Methods", jScrollPane3);

        jScrollPane4.setViewportView(classMethodList);

        jTabbedPane2.addTab("Static Methods", jScrollPane4);

        jScrollPane5.setViewportView(constructorList);

        jTabbedPane2.addTab("Constructors", jScrollPane5);

        jLabel1.setText("Methods");

        removeVariableButton.setText("-");

        addMetodButton.setText("+");

        removeMethodButton.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeVariableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addVariableButton))
                    .addComponent(variableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTabbedPane2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeMethodButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMetodButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variableLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVariableButton)
                    .addComponent(removeVariableButton)
                    .addComponent(addMetodButton)
                    .addComponent(removeMethodButton)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMetodButton;
    private javax.swing.JButton addVariableButton;
    private javax.swing.JList classMethodList;
    private javax.swing.JList classVaraibleList;
    private javax.swing.JList constructorList;
    private javax.swing.JList instanceMethodList;
    private javax.swing.JList instanceVariableList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton removeMethodButton;
    private javax.swing.JButton removeVariableButton;
    private javax.swing.JLabel variableLabel;
    // End of variables declaration//GEN-END:variables
}
