/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIShells.UIPanels;

import Models.PackageModel;
import Types.InnerType;
import UIShells.AddNewModelShell;
import javax.swing.DefaultListModel;

/**
 *
 * @author Arthur
 */
public class ClassListPanel extends BaseUIPanel {
    private PackageModel model;
    private DefaultListModel list;
    private InnerType desiredClass;

    /**
     * Creates new form ClassListPanel
     */
    public ClassListPanel() {
        initComponents();
    }
    
    public void setListModel(DefaultListModel list){
        modelList.setModel(list);
    }
    
    public void setUpModel(PackageModel model){
        list = new DefaultListModel();
        this.model = model;
        this.fillListModel(model.getClassList(), list);
        modelList.setModel(list);
    }
    
    private String getNewModelTitle(){
        if(this.desiredClass == InnerType.PACKAGE) {
            return "Package";
        } else {
            return "Class";
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modelList = new javax.swing.JList();
        addModelButton = new javax.swing.JButton();
        removeModelButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(modelList);

        addModelButton.setText("+");
        addModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelButtonActionPerformed(evt);
            }
        });

        removeModelButton.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(removeModelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addModelButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addModelButton)
                    .addComponent(removeModelButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelButtonActionPerformed
        new AddNewModelShell(this.model, this.desiredClass, list, this.getNewModelTitle());
    }//GEN-LAST:event_addModelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList modelList;
    private javax.swing.JButton removeModelButton;
    // End of variables declaration//GEN-END:variables
}
