/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIShells.UIForms;

import Models.*;

/**
 *
 * @author Arthur
 */
public class SelectedModelForm extends javax.swing.JPanel {
    private PackageModel selectedModel;
    private static final String defaultSource = "Unavailable";
    /**
     * Creates new form SelectedModelForm
     */
    public SelectedModelForm() {
        initComponents();
    }
    public SelectedModelForm(PackageModel selectedObject){
        this.selectedModel = selectedObject;
        initComponents();
        this.setFields();
        this.setVisible(true);
    }
    
    private void setFields(){
        modelDescriptionField.setText(selectedModel.getDescription());
        modelCommentField.setText(selectedModel.getComment());
        if(selectedModel.isMethod()) {
            methodSourceField.setText(selectedModel.toSourceString());
            methodSourceField.setEditable(true);
        }
        else{
            methodSourceField.setText(defaultSource);
            methodSourceField.setEditable(false);
        }
    }
    
    public void onSelectionChanged(PackageModel selection){
        this.selectedModel = selection;
        this.setFields();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelSelectorTabs = new javax.swing.JTabbedPane();
        methodSourceField = new javax.swing.JTextField();
        modelDescriptionField = new javax.swing.JTextField();
        modelCommentField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        methodSourceField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                methodSourceFieldPropertyChange(evt);
            }
        });
        modelSelectorTabs.addTab("Method Source", methodSourceField);

        modelDescriptionField.setEditable(false);
        modelDescriptionField.setColumns(3);
        modelSelectorTabs.addTab("Description", modelDescriptionField);
        modelSelectorTabs.addTab("Comment", modelCommentField);

        add(modelSelectorTabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void methodSourceFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_methodSourceFieldPropertyChange
       //a do nothing method... dammit netbeans!!!
    }//GEN-LAST:event_methodSourceFieldPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField methodSourceField;
    private javax.swing.JTextField modelCommentField;
    private javax.swing.JTextField modelDescriptionField;
    private javax.swing.JTabbedPane modelSelectorTabs;
    // End of variables declaration//GEN-END:variables
}
