/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPanels;

/**
 *
 * @author Arthur
 */
public class ClassEditingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClassEditingPanel
     */
    public ClassEditingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        methodSourceField = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        classCommentField = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(methodSourceField);

        jTabbedPane1.addTab("Source Code", jScrollPane1);

        jScrollPane2.setViewportView(classCommentField);

        jTabbedPane1.addTab("Description", jScrollPane2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane classCommentField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane methodSourceField;
    // End of variables declaration//GEN-END:variables
}
