/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPanels;

import MainBase.UsefulList;
import Models.BaseModel;
import Models.ClassModel;
import Models.MethodModel;
import Types.ClassType;
import UIModels.BrowserUIModel;
import javax.swing.JList;

/**
 *
 * @author Arthur
 */
public class MethodPanel extends BasePanel {

    /**
     * Creates new form MethodPanel
     */
    public MethodPanel() {
        initComponents();
        this.setUpLists();
    }
    
    @Override
    public void setModel(BrowserUIModel model){
        this.model = model;
        if(model.getSelectedClass() != null)
            this.fillListsFromClass(model.getSelectedClass());
    }
    
    private void fillListsFromClass(ClassModel aClass){
        for(MethodModel m : aClass.getMethods()){
            if(m.getType() == ClassType.STATIC)
                this.getListModel(staticMethodList).addElement(m);
            if(m.getType() == ClassType.INSTANCE)
                this.getListModel(instanceMethodList).addElement(m);
        }
    }
    
    @Override
    protected UsefulList<JList> myLists(){
        return super.myLists()
                .addElm(staticMethodList)
                .addElm(instanceMethodList);
    }
    
    @Override
    public void selectionChanged(BaseModel aClass){
        this.clearLists();
        if(aClass == null || !aClass.isClass())
            return;
        this.fillListsFromClass((ClassModel)aClass);
    }
    
    public ClassType getSelectedMethodType(){
        if(tabs.getSelectedIndex() == 1)
            return ClassType.STATIC;
        return ClassType.INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        instanceMethodList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        staticMethodList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        tabs.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tabs.setPreferredSize(new java.awt.Dimension(150, 250));

        jScrollPane1.setViewportView(instanceMethodList);

        tabs.addTab("Instance Methods", jScrollPane1);

        jScrollPane2.setViewportView(staticMethodList);

        tabs.addTab("Static Methods", jScrollPane2);

        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList instanceMethodList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList staticMethodList;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
