/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPanels;

/**
 *
 * @author Arthur
 */
public class ModelEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModelEditPanel
     */
    public ModelEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modelEditTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        modelEditTextArea.setColumns(20);
        modelEditTextArea.setRows(5);
        jScrollPane1.setViewportView(modelEditTextArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea modelEditTextArea;
    // End of variables declaration//GEN-END:variables
}
