/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPanels;

import Models.BaseModel;
import Models.MethodModel;
import UIModels.BrowserUIModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Arthur
 */
public class ModelEditPanel extends BasePanel{
    
    private BaseModel selectedModel;
    
    /**
     * Creates new form ModelEditPanel
     */
    public ModelEditPanel() {
        initComponents();
        this.modelEditTextArea.getDocument().addDocumentListener(this.setUpDocListener());
        this.commentTextArea.getDocument().addDocumentListener(this.setUpDocListener());
    }
    
    
    
    @Override
    public void setModel(BrowserUIModel aModel){
        this.model = aModel;
        this.setSelected(aModel.getSelected());
    }
    
    public void setSelected(BaseModel aModel){
        this.selectedModel = aModel;
        this.modelEditTextArea.setText(selectedModel.toSourceString());
        this.commentTextArea.setText(selectedModel.getComment());
        if(!selectedModel.isMethod())
            this.modelEditTextArea.setEditable(false);
    }
    
    private void updateModel(){
        if(selectedModel.isMethod())
            ((MethodModel)selectedModel).setSource(this.modelEditTextArea.getText());
    }
    
    private DocumentListener setUpDocListener(){
        return new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateModel();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                updateModel();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {}
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelEditTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        modelEditTextArea.setColumns(20);
        modelEditTextArea.setRows(5);
        jScrollPane1.setViewportView(modelEditTextArea);

        jTabbedPane1.addTab("Source", jScrollPane1);

        commentTextArea.setColumns(20);
        commentTextArea.setRows(5);
        jScrollPane2.setViewportView(commentTextArea);

        jTabbedPane1.addTab("Comment", jScrollPane2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea modelEditTextArea;
    // End of variables declaration//GEN-END:variables
}
