/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIPanels;

import Models.BaseModel;
import Models.ClassModel;
import Models.MethodModel;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthur
 */
public class ModelListPanel extends BasePanel {

    /**
     * Creates new form ModelListPanel
     */
    public ModelListPanel() {
        initComponents();
        this.setUpTable();
    }
    
    private DefaultTableModel tableModel(){
        return(DefaultTableModel)this.modelTable.getModel();
    }
    
    private void setUpTable(){
        this.modelTable.setModel(new DefaultTableModel());
    }
    
    public void addClassToList(ClassModel aClass){
        this.tableModel().addRow(
                new String[] {aClass.getScope().toString().toLowerCase(), 
                    aClass.name()});
    }
    
    public void addMethodToList(MethodModel aMethod){
        this.tableModel().addRow(
                new String[] 
                   {aMethod.scopeString(), 
                    aMethod.getReturnType().name(),
                    aMethod.getType().toString().toLowerCase()});
    }
    
    public void fillTable(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modelTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        modelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(modelTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable modelTable;
    // End of variables declaration//GEN-END:variables


    private class ModelVector<T> extends Vector<T>{
        
        
    }
    
    private enum ListType {
        CLASS, METHOD;
    }
}
