/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPanels;

/**
 *
 * @author Arthur
 */
public class SelectedClassPanel extends BasePanel {

    /**
     * Creates new form SelectedClassPanel
     */
    public SelectedClassPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        classFieldsPanel1 = new UIPanels.ClassFieldsPanel();
        methodPanel1 = new UIPanels.MethodPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setLeftComponent(classFieldsPanel1);
        jSplitPane1.setRightComponent(methodPanel1);

        jSplitPane2.setRightComponent(jSplitPane1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Classes");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setLeftComponent(jPanel1);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIPanels.ClassFieldsPanel classFieldsPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private UIPanels.MethodPanel methodPanel1;
    // End of variables declaration//GEN-END:variables
}
