/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIPanels.TreePanels;

import UIPanels.TreePanels.Nodes.PackageNode;
import javax.swing.JTree;

/**
 *
 * @author arthur
 */
public class PackageTreePanel extends BaseTreePanel {

    /**
     * Creates new form PackageTreePanel
     */
    public PackageTreePanel() {
        initComponents();
    }
    
    @Override
    public JTree tree(){
        return packageTree;
    }
    
    @Override
    public PackageNode getRootNode(){
        if(rootNode == null)
            rootNode = new PackageNode(controller.getSelectedProject().getAllPackage(), treeMap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packageTree = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        packageTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(packageTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Packages");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree packageTree;
    // End of variables declaration//GEN-END:variables
}
